const express = require('express');
const router = express.Router();
const DailyReport = require('../models/DailyReport');
const Billing = require('../models/Billing');
const Customer = require('../models/Customer');

// ─── GET daily report ─────────────────────────────────
router.get('/daily/:date', async (req, res) => {
  try {
    const report = await DailyReport.findOne({ dateString: req.params.date });
    if (!report) {
      return res.status(404).json({ 
        success: false, 
        message: 'Is date ka koi report nahi hai' 
      });
    }
    res.json({ success: true, data: report });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ─── GET recent daily reports ─────────────────────────
router.get('/daily', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 30;
    const reports = await DailyReport.find()
      .sort({ date: -1 })
      .limit(limit)
      .select('dateString totalTrips totalCustomersServed totalCansDelivered totalNormalCansDelivered totalCoolCansDelivered totalRevenue');
    res.json({ success: true, data: reports });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ─── GET monthly report ───────────────────────────────
router.get('/monthly/:year/:month', async (req, res) => {
  try {
    const { year, month } = req.params;
    const monthKey = `${year}-${String(month).padStart(2, '0')}`;
    
    // Get all daily reports for this month
    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endMonth = parseInt(month) === 12 ? 1 : parseInt(month) + 1;
    const endYear = parseInt(month) === 12 ? parseInt(year) + 1 : parseInt(year);
    const endDate = `${endYear}-${String(endMonth).padStart(2, '0')}-01`;
    
    const dailyReports = await DailyReport.find({
      dateString: { $gte: startDate, $lt: endDate }
    }).sort({ dateString: 1 });
    
    // Get billing data for this month
    const billingData = await Billing.find({ monthKey }).sort({ customerName: 1 });
    
    // Aggregate totals
    const totals = {
      totalDeliveryDays: dailyReports.length,
      totalTrips: dailyReports.reduce((sum, r) => sum + r.totalTrips, 0),
      totalCustomersServed: dailyReports.reduce((sum, r) => sum + r.totalCustomersServed, 0),
      totalNormalCansDelivered: dailyReports.reduce((sum, r) => sum + r.totalNormalCansDelivered, 0),
      totalCoolCansDelivered: dailyReports.reduce((sum, r) => sum + r.totalCoolCansDelivered, 0),
      totalCansDelivered: dailyReports.reduce((sum, r) => sum + r.totalCansDelivered, 0),
      totalEmptyCansCollected: dailyReports.reduce((sum, r) => sum + r.totalEmptyCansCollected, 0),
      totalBilled: billingData.reduce((sum, b) => sum + b.totalAmount, 0),
      totalPaid: billingData.reduce((sum, b) => sum + b.paidAmount, 0),
      totalPending: billingData.reduce((sum, b) => sum + b.pendingAmount, 0)
    };
    
    res.json({ 
      success: true, 
      data: { totals, dailyReports, billingData } 
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ─── GET WhatsApp report text (daily) ─────────────────
router.get('/whatsapp/daily/:date', async (req, res) => {
  try {
    const report = await DailyReport.findOne({ dateString: req.params.date });
    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found' });
    }
    
    let text = `🚰 *KK Events & Water Plant*\n`;
    text += `📅 *Daily Delivery Report*\n`;
    text += `📆 Date: ${req.params.date}\n`;
    text += `━━━━━━━━━━━━━━━━━━\n\n`;
    
    text += `📊 *Summary:*\n`;
    text += `• Total Trips: ${report.totalTrips}\n`;
    text += `• Customers Served: ${report.totalCustomersServed}\n`;
    text += `• Normal Cans: ${report.totalNormalCansDelivered}\n`;
    text += `• Cool Cans: ${report.totalCoolCansDelivered}\n`;
    text += `• Total Cans: ${report.totalCansDelivered}\n`;
    text += `• Empty Cans Collected: ${report.totalEmptyCansCollected}\n\n`;
    
    text += `📋 *Customer-wise Details:*\n`;
    text += `━━━━━━━━━━━━━━━━━━\n`;
    
    report.deliveryDetails.forEach((d, i) => {
      const time = d.deliveredAt ? new Date(d.deliveredAt).toLocaleTimeString('en-IN', { 
        hour: '2-digit', minute: '2-digit' 
      }) : '-';
      text += `${i + 1}. ${d.customerName}\n`;
      text += `   Normal: ${d.normalCans} | Cool: ${d.coolCans}`;
      text += ` | Time: ${time}\n`;
    });
    
    text += `\n━━━━━━━━━━━━━━━━━━\n`;
    text += `✅ Generated by KK Delivery App`;
    
    res.json({ success: true, data: { text, report } });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// ─── GET WhatsApp report text (monthly) ───────────────
router.get('/whatsapp/monthly/:year/:month', async (req, res) => {
  try {
    const { year, month } = req.params;
    const monthKey = `${year}-${String(month).padStart(2, '0')}`;
    const monthNames = ['', 'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'];
    
    const billingData = await Billing.find({ monthKey }).sort({ customerName: 1 });
    
    let text = `🚰 *KK Events & Water Plant*\n`;
    text += `📅 *Monthly Report - ${monthNames[parseInt(month)]} ${year}*\n`;
    text += `━━━━━━━━━━━━━━━━━━\n\n`;
    
    let totalBilled = 0, totalPaid = 0;
    
    billingData.forEach((b, i) => {
      text += `${i + 1}. *${b.customerName}*\n`;
      text += `   Normal: ${b.normalCansDelivered} × ₹${b.normalCanRate} = ₹${b.normalCansAmount}\n`;
      text += `   Cool: ${b.coolCansDelivered} × ₹${b.coolCanRate} = ₹${b.coolCansAmount}\n`;
      text += `   Total: ₹${b.totalAmount} | Paid: ₹${b.paidAmount} | Due: ₹${b.pendingAmount}\n`;
      text += `   Status: ${b.status === 'cleared' ? '✅ PAID' : b.status === 'partial' ? '⚠️ PARTIAL' : '❌ PENDING'}\n\n`;
      totalBilled += b.totalAmount;
      totalPaid += b.paidAmount;
    });
    
    text += `━━━━━━━━━━━━━━━━━━\n`;
    text += `💰 *Total Billed:* ₹${totalBilled}\n`;
    text += `✅ *Total Paid:* ₹${totalPaid}\n`;
    text += `⏳ *Total Pending:* ₹${totalBilled - totalPaid}\n`;
    text += `━━━━━━━━━━━━━━━━━━\n`;
    text += `✅ Generated by KK Delivery App`;
    
    res.json({ success: true, data: { text } });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;
